### ISSUE TITLE
Submit package to PyPI

### ISSUE THREAD

**Issue by rafaelcanovas** [dellis23/django-wordpress-auth#3]
Would be nice if this package was on PyPI, so we could install it with running `pip install django-wordpress-auth`.

**Comment by dellis23** [comment]
:+1: would you like to field this?  If not, I can look into it later to see how involved the process is.

**Comment by rafaelcanovas** [comment]
Sure, no problem.

**Comment by rafaelcanovas** [comment]
Done! https://pypi.python.org/pypi/django-wordpress-auth/

**Comment by dellis23** [comment]
:+1: awesome, well done!

**Comment by dellis23** [comment]
Appreciate the work.  I've added you as a collaborator if you decide you
want to see anything else done!
