### ISSUE TITLE
Documentation clarification on keys and salts from wp-config.php

### ISSUE THREAD

**Issue by pembo13** [dellis23/django-wordpress-auth#7]
> Add your WordPress's auth keys and salts (found in wp-config.php) to your settings.py.

The documentation should be clarified to specify that `LOGGED_IN_KEY` and `LOGGED_IN_SALT` from `wp-config.py` is what should be used specifically.

**Comment by dellis23** [comment]
Good catch.  Wanna throw a commit up?  Otherwise, I can do it later.

**Comment by pembo13** [comment]
I got as far as doing a clone of the repo, making the change, and creating
a commit, but I'm unfamiliar with getting that commit to you.

**Comment by dellis23** [comment]
You could fork the repo in github and push your changes to it.  That'll let me merge it with you getting credit for it.  If that sounds complicated though, you could just paste the output of the diff here and I can apply it.  You can do that by doing `git show <commitidhere>`.  You can get a list of recent commits by doing `git log`.  If it is your most recent commit (which I'm assuming it is), `git show HEAD` should work.

**Comment by pembo13** [comment]
Sorry, I have the will to do this, but not (yet) the time or the knowledge.
I hope to give it a try soon.

**Comment by pembo13** [comment]
@dellis23 Finally made the change, https://github.com/dellis23/django-wordpress-auth/pull/10

**Comment by dellis23** [comment]
Thanks!  Closing this now that the PR has been merged.
