### ISSUE TITLE
'NoneType' object has no attribute 'capabilities' or 'roles'

### ISSUE THREAD

**Issue by avipaul6** [dellis23/django-wordpress-auth#8]
I followed the instruction but cant get it to work. I get the error

'NoneType' object has no attribute 'capabilities' or 
'NoneType' object has no attribute 'roles' depending on what I was trying to pass. How can I solve this?

**Comment by dellis23** [comment]
I haven't touched this in years, but I'd guess the middleware isn't installed properly.  Full tracebacks would help, but I'm guessing it's referring to these lines?  https://github.com/dellis23/django-wordpress-auth/blob/ede7a1372d369ee3ac942e39b01c6b6f279f9c19/wordpress_auth/decorators.py#L20  https://github.com/dellis23/django-wordpress-auth/blob/ede7a1372d369ee3ac942e39b01c6b6f279f9c19/wordpress_auth/decorators.py#L31

**Comment by avipaul6** [comment]
noted. thank you. Will look into them.
